// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: protos/resi.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RedundancyTSN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tsn uint64 `protobuf:"varint,1,opt,name=tsn,proto3" json:"tsn,omitempty"`
}

func (x *RedundancyTSN) Reset() {
	*x = RedundancyTSN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_resi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedundancyTSN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedundancyTSN) ProtoMessage() {}

func (x *RedundancyTSN) ProtoReflect() protoreflect.Message {
	mi := &file_protos_resi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedundancyTSN.ProtoReflect.Descriptor instead.
func (*RedundancyTSN) Descriptor() ([]byte, []int) {
	return file_protos_resi_proto_rawDescGZIP(), []int{0}
}

func (x *RedundancyTSN) GetTsn() uint64 {
	if x != nil {
		return x.Tsn
	}
	return 0
}

type RedundancyMergeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cookie []byte `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
}

func (x *RedundancyMergeRequest) Reset() {
	*x = RedundancyMergeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_resi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedundancyMergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedundancyMergeRequest) ProtoMessage() {}

func (x *RedundancyMergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_resi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedundancyMergeRequest.ProtoReflect.Descriptor instead.
func (*RedundancyMergeRequest) Descriptor() ([]byte, []int) {
	return file_protos_resi_proto_rawDescGZIP(), []int{1}
}

func (x *RedundancyMergeRequest) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

type RedundancyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr   string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Cookie []byte `protobuf:"bytes,2,opt,name=cookie,proto3" json:"cookie,omitempty"`
}

func (x *RedundancyResponse) Reset() {
	*x = RedundancyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_resi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedundancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedundancyResponse) ProtoMessage() {}

func (x *RedundancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_resi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedundancyResponse.ProtoReflect.Descriptor instead.
func (*RedundancyResponse) Descriptor() ([]byte, []int) {
	return file_protos_resi_proto_rawDescGZIP(), []int{2}
}

func (x *RedundancyResponse) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RedundancyResponse) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

type RedundancyCookieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RedundancyCookieRequest) Reset() {
	*x = RedundancyCookieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_resi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedundancyCookieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedundancyCookieRequest) ProtoMessage() {}

func (x *RedundancyCookieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_resi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedundancyCookieRequest.ProtoReflect.Descriptor instead.
func (*RedundancyCookieRequest) Descriptor() ([]byte, []int) {
	return file_protos_resi_proto_rawDescGZIP(), []int{3}
}

type RedundancyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Ty:
	//	*RedundancyRequest_Cookie
	//	*RedundancyRequest_Merge
	Ty isRedundancyRequest_Ty `protobuf_oneof:"ty"`
}

func (x *RedundancyRequest) Reset() {
	*x = RedundancyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_resi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedundancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedundancyRequest) ProtoMessage() {}

func (x *RedundancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_resi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedundancyRequest.ProtoReflect.Descriptor instead.
func (*RedundancyRequest) Descriptor() ([]byte, []int) {
	return file_protos_resi_proto_rawDescGZIP(), []int{4}
}

func (m *RedundancyRequest) GetTy() isRedundancyRequest_Ty {
	if m != nil {
		return m.Ty
	}
	return nil
}

func (x *RedundancyRequest) GetCookie() *RedundancyCookieRequest {
	if x, ok := x.GetTy().(*RedundancyRequest_Cookie); ok {
		return x.Cookie
	}
	return nil
}

func (x *RedundancyRequest) GetMerge() *RedundancyMergeRequest {
	if x, ok := x.GetTy().(*RedundancyRequest_Merge); ok {
		return x.Merge
	}
	return nil
}

type isRedundancyRequest_Ty interface {
	isRedundancyRequest_Ty()
}

type RedundancyRequest_Cookie struct {
	Cookie *RedundancyCookieRequest `protobuf:"bytes,1,opt,name=cookie,proto3,oneof"`
}

type RedundancyRequest_Merge struct {
	Merge *RedundancyMergeRequest `protobuf:"bytes,2,opt,name=merge,proto3,oneof"`
}

func (*RedundancyRequest_Cookie) isRedundancyRequest_Ty() {}

func (*RedundancyRequest_Merge) isRedundancyRequest_Ty() {}

var File_protos_resi_proto protoreflect.FileDescriptor

var file_protos_resi_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x21, 0x0a, 0x0d, 0x52,
	0x65, 0x64, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x63, 0x79, 0x54, 0x53, 0x4e, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x74, 0x73, 0x6e, 0x22, 0x30,
	0x0a, 0x16, 0x52, 0x65, 0x64, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x63, 0x79, 0x4d, 0x65, 0x72, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x6b,
	0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65,
	0x22, 0x40, 0x0a, 0x12, 0x52, 0x65, 0x64, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f,
	0x6f, 0x6b, 0x69, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x6f, 0x6f, 0x6b,
	0x69, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x52, 0x65, 0x64, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x63, 0x79,
	0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8c, 0x01,
	0x0a, 0x11, 0x52, 0x65, 0x64, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x64,
	0x75, 0x6e, 0x64, 0x61, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x12, 0x36,
	0x0a, 0x05, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x63,
	0x79, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x05, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x42, 0x04, 0x0a, 0x02, 0x74, 0x79, 0x42, 0x2c, 0x5a, 0x2a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x61, 0x74, 0x65, 0x66,
	0x75, 0x6c, 0x6d, 0x6f, 0x72, 0x6f, 0x6e, 0x2f, 0x72, 0x65, 0x73, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protos_resi_proto_rawDescOnce sync.Once
	file_protos_resi_proto_rawDescData = file_protos_resi_proto_rawDesc
)

func file_protos_resi_proto_rawDescGZIP() []byte {
	file_protos_resi_proto_rawDescOnce.Do(func() {
		file_protos_resi_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_resi_proto_rawDescData)
	})
	return file_protos_resi_proto_rawDescData
}

var file_protos_resi_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_resi_proto_goTypes = []interface{}{
	(*RedundancyTSN)(nil),           // 0: protos.RedundancyTSN
	(*RedundancyMergeRequest)(nil),  // 1: protos.RedundancyMergeRequest
	(*RedundancyResponse)(nil),      // 2: protos.RedundancyResponse
	(*RedundancyCookieRequest)(nil), // 3: protos.RedundancyCookieRequest
	(*RedundancyRequest)(nil),       // 4: protos.RedundancyRequest
}
var file_protos_resi_proto_depIdxs = []int32{
	3, // 0: protos.RedundancyRequest.cookie:type_name -> protos.RedundancyCookieRequest
	1, // 1: protos.RedundancyRequest.merge:type_name -> protos.RedundancyMergeRequest
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_resi_proto_init() }
func file_protos_resi_proto_init() {
	if File_protos_resi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_resi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RedundancyTSN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_resi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RedundancyMergeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_resi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RedundancyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_resi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RedundancyCookieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_resi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RedundancyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_resi_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*RedundancyRequest_Cookie)(nil),
		(*RedundancyRequest_Merge)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_resi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_resi_proto_goTypes,
		DependencyIndexes: file_protos_resi_proto_depIdxs,
		MessageInfos:      file_protos_resi_proto_msgTypes,
	}.Build()
	File_protos_resi_proto = out.File
	file_protos_resi_proto_rawDesc = nil
	file_protos_resi_proto_goTypes = nil
	file_protos_resi_proto_depIdxs = nil
}
